
# platform :ios, ‘8.0’

target 'baseFramework' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


pod 'AFNetworking', '~> 3.1.0'

pod 'SDWebImage', '~> 3.7.6’

pod 'MBProgressHUD', '~> 0.9.2'

pod 'SVProgressHUD', '~> 2.0.3'

pod 'MJRefresh', '~> 3.1.0'

pod 'MJExtension', '~> 3.0'

pod 'IQKeyboardManager', '~> 3.3.7'

pod 'Masonry', '~> 1.0.0'

pod 'SFFoundation'

  # Pods for baseFramework

end
